Itemwise Monthly Fencing Production Report
thirvusoft/paver_sgp pull request #282
Opened 2022-11-15 06:51 UTC by Gokulnath17

![image](https://user-images.githubusercontent.com/95605271/201849190-de97d99a-d2c2-44e3-9612-fc2dc9ff8b9a.png)

2022-11-15 09:58 UTC, Ponnusamy1-V commented
Add a item filter, that will lists items with below filters:
     ```item_group```: ```Compound Wall```
     ```type```: ```Fencing Post```

2022-11-15 10:00 UTC, Ponnusamy1-V requested changes

2022-11-15 10:03 UTC, Ponnusamy1-V commented
> Add a item filter, that will lists items with below filters: `item_group`: `Compound Wall` `type`: `Fencing Post`

No need

2022-11-15 11:15 UTC, Ponnusamy1-V commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +					sub_list = []
Why are you using `list` instead of `dict`

2022-11-15 11:16 UTC, Ponnusamy1-V commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +	if doc:
is the if statement is necessary?

2022-11-15 11:20 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +					sub_list = []
For report list also accept then why i use dict? please explain the dict use here.

2022-11-15 11:20 UTC, Ponnusamy1-V requested changes

2022-11-15 11:20 UTC, Ponnusamy1-V commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +						sub_list = []
need justification for using `list` without using `dict`

2022-11-15 11:20 UTC, Ponnusamy1-V commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +			row[6] = row[6] / row[7]
if `row[7]` equals `0`, an error will occur

2022-11-15 11:23 UTC, Ponnusamy1-V commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +					sub_list = []
while using `list` it will take the value based on that index, that may lead an issue while adding new column. Also u must have to specify the value for that index. While using `dict` the above issues won't occur

2022-11-15 11:26 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +	if doc:
Not necessary, once we check it. so there is no problem

2022-11-15 11:33 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +			row[6] = row[6] / row[7]
there is no way row[7] is 0 because it will not enter in the 17 line itself

2022-11-15 11:34 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +						sub_list = []
I will check the data already it come or not, if need changes u will change and commit

2022-11-15 11:41 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +					sub_list = []
As per the requirement given, I will add all the columns in the report, then why there are changes that mean you do not clarify with the client?

2022-11-15 11:42 UTC, Ponnusamy1-V commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +	if doc:
Kindly don't mark this resolved until removing the `if` statement

2022-11-15 11:43 UTC, Ponnusamy1-V commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +					sub_list = []
If client gives new column as a requirement , then we have to add a new column

2022-11-15 11:44 UTC, Ponnusamy1-V commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +					sub_list = []
Kindly mention the advantages of using `list` over `dict`

2022-11-15 11:45 UTC, Ponnusamy1-V commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +						sub_list = []
No @Gokulnath17, kindly understand what i try to say.

2022-11-15 11:48 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +	if doc:
if I remove if statement, it will check 2 for loops, if there is an if statement there is only one line execution other wise there is 2 line execution

2022-11-15 11:49 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +	if doc:
Now you will resole this conversation by your hand itself.

2022-11-15 11:49 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +	if doc:
No its ok

2022-11-15 11:53 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +					sub_list = []
if I add dict there are some extra codes if the client asks you will add that as last column

2022-11-15 11:54 UTC, Ponnusamy1-V commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +	if doc:
No, for loop will not execute if the doc is empty, so i think if is not necessary here

2022-11-15 11:56 UTC, Ponnusamy1-V commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +					sub_list = []
While using `list`, if we want to rearrange the columns, then we have to change at many places.

2022-11-15 12:37 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +					sub_list = []
changed to dict

2022-11-15 12:38 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +	if doc:
2 for loop work if statement is not there, so I am cannot able to remove that

2022-11-15 12:38 UTC, Gokulnath17 commented on ganapathy_pavers/ganapathy_pavers/report/itemwise_monthly_fencing_production_report/itemwise_monthly_fencing_production_report.py
> +						sub_list = []
changed to dict

2022-11-17 04:27 UTC, Ponnusamy1-V approved these changes

2022-11-17 04:36 UTC, merged